Fix create_node_allocation
PteroPackages/Pytero pull request #7
Opened 2023-06-27 07:37 UTC by brodokk

If you look at the  [Pterodactyl documentation](https://dashflo.net/docs/api/pterodactyl/v1/) `Create allocations` the API will return a 204 with no content

2023-07-01 17:44 UTC, devnote-dev requested changes

2023-07-01 17:44 UTC, devnote-dev commented on pytero/app.py
> +            Alias name of the node.
```suggestion
            The IP for the allocation.
        ports: :class:`list[str]`
            A list of ports or port ranges for the allocation.
        alias: :class:`str`
            Alias name of the node.
```

2023-07-01 17:44 UTC, devnote-dev commented on pytero/app.py
>          data = await self._http.post(
```suggestion
        await self._http.post(
```

2023-07-03 05:30 UTC, brodokk commented
Hey, thanks for your propositions. I actually update a bit more what you was proposing for the documentation part to make it more consistent.

2023-07-03 17:33 UTC, devnote-dev requested changes

2023-07-03 17:33 UTC, devnote-dev commented on pytero/app.py
> +        """ Create a new allocated node.
It's creating a node allocation, not a node.
```suggestion
        """ Create a new node allocation.
```

2023-07-03 17:33 UTC, devnote-dev commented on pytero/app.py
> +            The ID of the allocation.
This isn't the allocation ID, it's the node ID. The allocation ID wouldn't exist yet.

2023-07-03 17:51 UTC, brodokk commented
Sorry for this mistakes, should be good now

2023-07-03 17:53 UTC, devnote-dev approved these changes

2023-07-03 17:54 UTC, merged